# Generated by Django 2.2.6 on 2020-01-22 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_title', models.TextField(help_text='Example: For a project, as a partner or as a team.')),
                ('contact_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(help_text='Image size: width: 1422px height: 711px', upload_to='contact/')),
            ],
            options={
                'verbose_name': '1. Contact Us Page Content',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('number', models.CharField(blank=True, max_length=50, null=True)),
                ('address', models.CharField(blank=True, max_length=100, null=True)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('message', models.TextField()),
            ],
            options={
                'verbose_name': "2.(Not for inserting data) User's Message",
            },
        ),
    ]
