# Generated by Django 2.2.6 on 2020-01-22 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(help_text='Image size: width=1885px height=931px', upload_to='process/')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(help_text='Image size: width=289px height=296px', upload_to='process/')),
                ('step_description', models.TextField()),
            ],
        ),
    ]
