# Generated by Django 2.2.5 on 2019-09-06 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(help_text='Image size: width=193px height=115px', upload_to='index/')),
                ('description', models.CharField(max_length=100)),
            ],
        ),
    ]
