# Generated by Django 2.2.5 on 2019-09-06 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='description',
            field=models.TextField(),
        ),
    ]
