# Generated by Django 2.2.5 on 2019-09-06 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_organization'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessMain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(help_text='Image size: width=193px height=115px', upload_to='process/')),
                ('title', models.TextField(blank=True, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(help_text='Image size: width=193px height=115px', upload_to='solution/')),
                ('title', models.TextField(blank=True, null=True)),
                ('description1', models.TextField()),
                ('description2', models.TextField()),
            ],
        ),
    ]
