# Generated by Django 2.2.5 on 2019-09-06 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_processmain_solution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='title',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='processmain',
            name='title',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='solution',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
