# Generated by Django 2.2.5 on 2019-09-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20190906_1150'),
    ]

    operations = [
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('image', models.ImageField(upload_to='process/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='processmain',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
