# Generated by Django 2.2.5 on 2019-09-06 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20190906_1155'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('icon', models.ImageField(upload_to='process/')),
                ('description', models.TextField()),
            ],
        ),
    ]
