# Generated by Django 2.2.5 on 2019-09-06 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='about/')),
                ('secondary_image', models.ImageField(upload_to='about/')),
                ('video', models.FileField(upload_to='videos/')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='contact/')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='project/')),
            ],
        ),
        migrations.AddField(
            model_name='project',
            name='sector',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
