# Generated by Django 2.2.5 on 2019-09-06 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_auto_20190906_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='slogan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='item.Project'),
        ),
    ]
