# Generated by Django 2.2.5 on 2019-09-09 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_auto_20190909_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solution',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
