# Generated by Django 2.2.5 on 2019-09-09 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0017_auto_20190909_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='process',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='processmain',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
