# Generated by Django 2.2.5 on 2019-09-09 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0019_auto_20190909_1231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.TextField(blank=True, null=True),
        ),
    ]
