# Generated by Django 2.2.5 on 2019-09-09 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0020_auto_20190909_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='about',
            name='video',
            field=models.URLField(blank=True, null=True),
        ),
    ]
