# Generated by Django 2.2.5 on 2019-09-16 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0022_auto_20190909_1404'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(upload_to='about/')),
                ('secondary_image', models.ImageField(upload_to='about/')),
                ('video_url', models.URLField(verbose_name='Please enter the url of the video from youtube or other sources')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.RenameModel(
            old_name='ContactForm',
            new_name='Message',
        ),
        migrations.DeleteModel(
            name='About',
        ),
    ]
