# Generated by Django 2.2.5 on 2019-09-16 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0023_auto_20190916_1043'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_title', models.TextField(help_text='Example: For a project, as a partner or as a team.')),
                ('contact_description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='contact/')),
            ],
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='video_url',
            field=models.URLField(help_text='Please enter the url of the video from youtube or other sources'),
        ),
    ]
