# Generated by Django 2.2.5 on 2019-09-16 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0024_auto_20190916_1051'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='Image size: width=193px height=115px', upload_to='index/')),
            ],
        ),
        migrations.DeleteModel(
            name='Index',
        ),
    ]
