# Generated by Django 2.2.5 on 2019-09-16 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0025_auto_20190916_1056'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProcessStep',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_name', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='process/')),
                ('step_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SolutionWeProvide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_name', models.TextField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='solution/')),
            ],
        ),
        migrations.RenameModel(
            old_name='ProcessMain',
            new_name='ProcessPage',
        ),
        migrations.RenameModel(
            old_name='Solution',
            new_name='SolutionPage',
        ),
        migrations.DeleteModel(
            name='Process',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='description',
            new_name='project_description',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='title',
            new_name='project_name',
        ),
        migrations.RenameField(
            model_name='project',
            old_name='project_type',
            new_name='project_status',
        ),
        migrations.RenameField(
            model_name='service',
            old_name='title',
            new_name='service_name',
        ),
        migrations.AddField(
            model_name='organization',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_address',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='organization_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='organization',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
