# Generated by Django 2.2.5 on 2019-09-16 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0026_auto_20190916_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solutionpage',
            name='description1',
        ),
        migrations.RemoveField(
            model_name='solutionpage',
            name='description2',
        ),
    ]
