# Generated by Django 2.2.5 on 2019-09-16 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0027_auto_20190916_1117'),
    ]

    operations = [
        migrations.RenameField(
            model_name='organization',
            old_name='slogan',
            new_name='company_slogan',
        ),
    ]
