# Generated by Django 2.2.5 on 2019-09-16 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0029_auto_20190916_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='company_slogan',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
