# Generated by Django 2.2.5 on 2019-09-16 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0030_auto_20190916_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectOverView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField()),
                ('description', models.TextField()),
            ],
        ),
    ]
