# Generated by Django 2.2.5 on 2019-09-17 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0032_auto_20190916_1421'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='main_image',
            field=models.ImageField(help_text='Image size: width: 1422px height: 711px', upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='secondary_image',
            field=models.ImageField(help_text='Image size: width=585px height=342px', upload_to='about/'),
        ),
        migrations.AlterField(
            model_name='contactdetail',
            name='image',
            field=models.ImageField(help_text='Image size: width: 1422px height: 711px', upload_to='contact/'),
        ),
        migrations.AlterField(
            model_name='homepageimage',
            name='image',
            field=models.ImageField(help_text='Image size: width=1220px height=927px', upload_to='index/'),
        ),
        migrations.AlterField(
            model_name='processpage',
            name='main_image',
            field=models.ImageField(help_text='Image size: width=1885px height=931px', upload_to='process/'),
        ),
        migrations.AlterField(
            model_name='processstep',
            name='image',
            field=models.ImageField(help_text='Image size: width=289px height=296px', upload_to='process/'),
        ),
        migrations.AlterField(
            model_name='projectimage',
            name='image',
            field=models.ImageField(help_text='Image size: width: 900px height: 879px', upload_to='project/'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.ImageField(help_text='Image size: width=71px height=68px', upload_to='process/'),
        ),
        migrations.AlterField(
            model_name='solutionpage',
            name='main_image',
            field=models.ImageField(help_text='Image size: width=1220px height=711px', upload_to='solution/'),
        ),
        migrations.AlterField(
            model_name='solutionweprovide',
            name='image',
            field=models.ImageField(help_text='Image size: width=711px height=410px', upload_to='solution/'),
        ),
    ]
