# Generated by Django 2.2.5 on 2019-09-24 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0033_auto_20190917_1306'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='thumbnail_image',
            field=models.ImageField(blank=True, help_text='Image size: width=585px height=342px', null=True, upload_to='thumbnail/'),
        ),
    ]
