# Generated by Django 2.2.6 on 2020-01-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0034_aboutus_thumbnail_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='SolutionPage',
        ),
        migrations.DeleteModel(
            name='SolutionWeProvide',
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='thumbnail_image',
            field=models.ImageField(help_text='Image size: width=840px height=558px', upload_to='thumbnail/'),
        ),
    ]
