# Generated by Django 2.2.6 on 2020-01-22 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0035_auto_20200122_0635'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProcessPage',
        ),
        migrations.DeleteModel(
            name='ProcessStep',
        ),
    ]
