# Generated by Django 2.2.6 on 2020-01-22 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0036_auto_20200122_0639'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectimage',
            name='project',
        ),
        migrations.DeleteModel(
            name='ProjectOverView',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='ProjectImage',
        ),
    ]
