# Generated by Django 2.2.6 on 2020-01-22 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0037_auto_20200122_0649'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AboutUs',
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
