# Generated by Django 2.2.6 on 2020-01-22 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0038_auto_20200122_0658'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContactDetail',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
