# Generated by Django 2.2.6 on 2020-01-22 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.ImageField(help_text='Image size: width: 1422px height: 711px', upload_to='about/')),
                ('secondary_image', models.ImageField(help_text='Image size: width=585px height=342px', upload_to='about/')),
                ('thumbnail_image', models.ImageField(help_text='Image size: width=840px height=558px', upload_to='thumbnail/')),
                ('video_url', models.URLField(help_text='Please enter the url of the video from youtube or other sources')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': '1. About Us Page Content',
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(blank=True, max_length=100, null=True)),
                ('organization_address', models.CharField(blank=True, max_length=100, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('organization_heading', models.TextField()),
                ('description', models.TextField()),
                ('company_slogan', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name': '2. Organization Detail',
            },
        ),
    ]
