# Generated by Django 2.2.6 on 2020-01-22 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('solutions_page', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '3. Service'},
        ),
        migrations.AlterModelOptions(
            name='solutionpage',
            options={'verbose_name': '1. Solution Page'},
        ),
        migrations.AlterModelOptions(
            name='solutionweprovide',
            options={'verbose_name': '2. Solution We Provide'},
        ),
    ]
